/**
 * Legal page content.
 *
 * Written to describe what this site actually does — the fields in lead.ts,
 * the processors in api/lead/route.ts, and the cookie-free analytics in
 * layout.tsx. A boilerplate policy that misdescribes the processing is worse
 * than none, because it is a statement to the regulator as well as to the
 * visitor. If the forms or processors change, change this too.
 */
import { site } from "@/lib/site";

/** Last substantive review of the legal pages. Update when the content changes. */
export const legalUpdated = "29 September 2026";

export const privacySections = [
  {
    heading: "Who is responsible for your data",
    body: [
      `${site.legalName} is the data controller for information collected through this website. If you have any question about how your data is handled, or you want it deleted, email ${site.contactEmail} and it will be dealt with.`,
    ],
  },
  {
    heading: "What is collected, and when",
    body: [
      "Nothing is collected unless you send it. Browsing the site does not require you to give any personal details.",
      "When you submit the contact, quote or booking form, the following is collected: your name, your email address, and — if you choose to give them — your phone number, the type of work you are enquiring about, your budget, your timeline, and whatever you write in the message field.",
      "Enquiries are stored in a database as well as emailed, so that nothing is lost if an email fails to arrive, and so there is a record of what was discussed.",
      "If you go on to become a client, records of your project are also kept: your business details, the brief you provide, project status, invoices, and any messages sent through the client portal.",
      "Your IP address is briefly held in memory to limit how many submissions can be made in a short period. This is a spam protection measure. It is not stored, not logged to a database, and is discarded when the server instance recycles.",
    ],
  },
  {
    heading: "Why it is collected",
    body: [
      "To reply to your enquiry and, if you go ahead, to carry out and administer the work — quoting, keeping track of the project, invoicing, and answering your questions. Your details are not used for marketing, not added to a mailing list, and not sold or shared with anyone for their own purposes.",
      "The lawful basis is legitimate interests — you have contacted a business asking for a service, and replying to you is the obvious and expected outcome. Where an enquiry becomes a project, the basis is performance of a contract.",
    ],
  },
  {
    heading: "Who else processes it",
    body: [
      "Two services are involved in running this site, and both are bound by their own data protection obligations:",
      "Resend delivers the emails generated by the forms. Your submission passes through their systems so that it can reach my inbox and so that your confirmation email can reach you. Resend is based in the United States, and this transfer is covered by standard contractual clauses.",
      "Vercel hosts the site and provides its analytics. The analytics are aggregate and cookie-free: they count page views and measure loading performance. They do not use cookies, do not fingerprint your device, and cannot identify you.",
      "Supabase provides the database where enquiries and client records are stored, and the sign-in system behind the client portal. Data is held in their European infrastructure.",
    ],
  },
  {
    heading: "Cookies",
    body: [
      "The public site sets no cookies. There is no tracking, no advertising pixel and no third-party script following you between sites, which is why you have not been asked to accept anything.",
      "Signing in to the client portal sets one cookie, which keeps you signed in. It is strictly necessary for the portal to work and is not used for tracking, so no consent banner is required for it. Signing out removes it.",
    ],
  },
  {
    heading: "The client portal",
    body: [
      "Clients can be given access to a portal showing their project, invoices and messages. Sign-in is by a link emailed to you — no password is set or stored.",
      "Access is restricted at the database level, so an account can only ever read records belonging to that client. Access can be revoked at any time, and takes effect immediately.",
    ],
  },
  {
    heading: "How long it is kept",
    body: [
      "Enquiry emails are kept for as long as there is a reasonable prospect of doing business, and are then deleted. Where an enquiry becomes a paid project, records are kept for six years after the work finishes, which is the period HMRC requires for business records.",
      "You can ask for your details to be deleted sooner, and unless there is a legal obligation to keep them, they will be.",
    ],
  },
  {
    heading: "Your rights",
    body: [
      "Under UK GDPR you can ask for a copy of the personal data held about you, ask for it to be corrected or deleted, object to it being processed, or ask for processing to be restricted. There is no charge, and a response will be given within one month.",
      `To exercise any of these, email ${site.contactEmail}.`,
      "If you are not satisfied with how a request has been handled, you can complain to the Information Commissioner's Office at ico.org.uk, which regulates data protection in the UK.",
    ],
  },
  {
    heading: "Changes to this policy",
    body: [
      "If how data is handled changes, this page changes with it, and the date at the top is updated.",
    ],
  },
] as const;

export const termsSections = [
  {
    heading: "About these terms",
    body: [
      `These terms cover the use of this website. The terms covering a project are set out separately in the written quote you receive before any work begins, and that quote is what governs the work itself.`,
    ],
  },
  {
    heading: "Quotes and prices",
    body: [
      "Prices shown on this site are starting points, given in good faith to help you judge whether the service fits your budget. They are not an offer and do not form a contract.",
      "The price for your project is the one in your written quote. That price is fixed for the scope described in it. If you later ask for work outside that scope, it is quoted separately and agreed before it is carried out — you will not receive an invoice for something you did not agree to.",
    ],
  },
  {
    heading: "What you provide",
    body: [
      "You are responsible for the accuracy of the content you supply, and for holding the rights to any text, images or logos you send. Please do not send material you do not have permission to use.",
      "Where a project stalls because content or feedback has not come back, the timeline moves accordingly. This is the most common cause of delay, and it is worth knowing in advance.",
    ],
  },
  {
    heading: "Ownership",
    body: [
      "On final payment, the website and its content are yours. There is no licence to buy back, no lock-in, and no hostage-taking of your domain or hosting.",
      "Third-party components used in the build stay under their own licences, and the right to show the finished work as a portfolio example is retained unless you ask otherwise.",
    ],
  },
  {
    heading: "This website's content",
    body: [
      "The text, design and images on this site are owned by " + site.legalName + ". Screenshots of client work are shown with the permission of those clients and remain their property.",
      "The guidance on this site is general information, not professional advice for your specific circumstances.",
    ],
  },
  {
    heading: "Liability",
    body: [
      "Nothing in these terms limits liability for death or personal injury caused by negligence, for fraud, or for anything else that cannot lawfully be limited.",
      "Subject to that, liability for a project is limited to the fees paid for it. No responsibility is accepted for indirect or consequential losses, such as lost profits or lost business.",
    ],
  },
  {
    heading: "Governing law",
    body: [
      "These terms are governed by the law of England and Wales, and the courts of England and Wales have jurisdiction.",
    ],
  },
] as const;
